#! /bin/bash

PROJECT_ROOT=$PWD
DST_FILE_PATH="${PROJECT_ROOT}/code/BotApp_Packed/BotPacked.cpp"
GENERATED_SCRIPT_PATH="${PROJECT_ROOT}/code/BotApp_Packed/copy_packed_file_to_wnd_host.sh"

echo "#! /bin/bash" > $GENERATED_SCRIPT_PATH
echo "# The script is generated by vs_wsl_setup.bat" >> $GENERATED_SCRIPT_PATH
echo "SRC_FILE_PATH=\$1" >> $GENERATED_SCRIPT_PATH
echo "cp -f \$SRC_FILE_PATH $DST_FILE_PATH" >> $GENERATED_SCRIPT_PATH

echo "The script is generated"